update coding convention in mutating scripts
Signed-off-by: Idan Kedar <idank@primarydata.com>

diff --git a/src/bin/extract b/src/bin/extract
--- a/src/bin/extract
+++ b/src/bin/extract
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-PROGRAM=`basename $0`
+PROGRAM=$(basename $0)
 DESCRIPTION="generic extract from archive."
 PARAMS="file-name"
 OPTIONS="[-h]"
@@ -27,51 +27,48 @@ EOF
     exit $1
 }
 
+die()
+{
+	RC=$1
+	shift
+	errcho "$*"
+	exit $RC
+}
+
 unrpm()
 {
 	RPM=$(readlink -f "$1")
-	DEST_DIR=$(basename ${RPM%.rpm})
-	mkdir "$DEST_DIR" && cd "$DEST_DIR" && rpm2cpio $RPM | cpio -idmv
+	DEST_DIR=$(basename "${RPM%.rpm}")
+	mkdir "$DEST_DIR" && cd "$DEST_DIR" && rpm2cpio "$RPM" | cpio -idmv
 }
 
-extractFile()
-{
-	case "$1" in
-		*.tar.bz2)	tar xvjf "$1" ;;
-		*.tar.xz)	tar xvJf "$1" ;;
-		*.tar.gz)	tar xvzf "$1" ;;
-		*.bz2)		bunzip2 "$1" ;;
-		*.rar)		unrar x "$1" ;;
-		*.ace)		unace x "$1" ;;
-		*.gz)		gunzip "$1" ;;
-		*.tar)		tar xvf "$1" ;;
-		*.tbz2)		tar xvjf "$1" ;;
-		*.tgz)		tar xvzf "$1" ;;
-		*.zip)		unzip "$1" ;;
-		*.Z)		uncompress "$1" ;;
-		*.7z)		7z x "$1" ;;
-		*.xz)		xz -d "$1" ;;
-		*.rpm)		unrpm "$1" ;;
-		*)			echo "$PROGRAM: '$1': extraction tool not found" ; return 1 ;;
+while getopts h OPTION; do
+	case $OPTION in
+		h) usage 0 ;;
+		\?) usage 2 ;;
 	esac
-}
-
-while getopts h option; do
-    case $option in
-        h) usage 0 ;;
-        \?) usage 2 ;;
-    esac
 done
-shift `expr $OPTIND - 1`
+shift $((OPTIND - 1))
 
-if [ $# -eq 0 ]; then
-	usage 2
-fi
+[ $# -eq 1 ] || usage 2
 
-if [ ! -f "$1" ]; then
-	echo "$PROGRAM: $1 does not exist"
-	exit 3
-fi
+[ -f "$1" ] || die 3 "$PROGRAM: '$1' does not exist"
 
-extractFile "$1"
-
+case "$1" in
+	*.tar.bz2)	tar xvjf "$1" ;;
+	*.tar.xz)	tar xvJf "$1" ;;
+	*.tar.gz)	tar xvzf "$1" ;;
+	*.bz2)		bunzip2 "$1" ;;
+	*.rar)		unrar x "$1" ;;
+	*.ace)		unace x "$1" ;;
+	*.gz)		gunzip "$1" ;;
+	*.tar)		tar xvf "$1" ;;
+	*.tbz2)		tar xvjf "$1" ;;
+	*.tgz)		tar xvzf "$1" ;;
+	*.zip)		unzip "$1" ;;
+	*.Z)		uncompress "$1" ;;
+	*.7z)		7z x "$1" ;;
+	*.xz)		xz -d "$1" ;;
+	*.rpm)		unrpm "$1" ;;
+	*) die 1  "$PROGRAM: '$1': extraction tool not found" ;;
+esac
diff --git a/src/bin/insertext b/src/bin/insertext
--- a/src/bin/insertext
+++ b/src/bin/insertext
@@ -1,10 +1,10 @@
-#! /bin/sh
+#! /bin/bash
 # #############################################################################
 
-       NAME_="insertext"
+       NAME_=$(basename $0)
        HTML_="put text into file"
     PURPOSE_="insert text file into another file at line n"
-   SYNOPSIS_="$NAME_ [-hl] <n> <text_file_to_insert> <file> [<file>..]"
+   SYNOPSIS_="$NAME_ [-h] <n> <text_file_to_insert> <file> [<file>..]"
    REQUIRES_="standard GNU commands"
     VERSION_="1.1"
        DATE_="2001-06-23; last update: 2005-03-30"
@@ -27,17 +27,24 @@ Options:
      <n>, an integer referring to line number at which to insert the text file
      <text_file_to_insert>, the text file to insert
      <file>, the text file to insert into
-     -h, usage and options (this help)
-     -l, see this script"
+     -h, usage and options (this help)"
     exit 1
 }
 
+die()
+{
+	RC=$1
+	shift
+	errcho "$*"
+	exit $RC
+}
+
 # tmp files setup
-tmp_1=/tmp/tmp.${RANDOM}$$
-tmp_2=/tmp/tmp.${RANDOM}$$
+TMP1=$(mktemp)
+TMP2=$(mktemp)
 
 # signal trapping and tmp file removal
-trap 'rm -f $tmp_1 $tmp_2 >/dev/null 2>&1' 0
+trap 'rm -f "$TMP1" "$TMP2" >/dev/null 2>&1' 0
 trap "exit 1" 1 2 3 15
 
 # enabling extended globbing
@@ -45,45 +52,30 @@ shopt -s extglob
 
 # option handling
 case "$1" in
-    -h) usage ;;
-    -l) more $0; exit 1 ;;
-    +([0-9])) # arg1 must be an integer
-
-        n=$1
-        [[ $# < 3 ]] && { errcho "missing argument"; exit 1; }
-        [ -e $2 ] || { errcho "file $2 does not exist"; exit 1; }
-        insert=$2
-        shift 2
-
-        for a in $@; do
-
-            if [ -f $a ]; then
-
-            # in case we want to insert at line 1
-            if [[ $n == 1 ]];then
-
-                touch $tmp_1
-                sed -n ''$n',$p' $a > $tmp_2
-                cat $tmp_1 $insert $tmp_2 > $a
-                continue
-
-            fi
-
-            ((n--)) # back up one line
-            sed -n '1,'$n'p' $a > $tmp_1
-            ((n++)) # back to original n
-            sed -n ''$n',$p' $a > $tmp_2
-            cat $tmp_1 $insert $tmp_2 > $a
-
-        else
-
-            echo $a does not exist or is not a file
-
-        fi
-
-    done ;;
-
-
-    *) echo invalid argument, type $NAME_ -h for help; exit 1 ;;
-
+	-h) usage ;;
+	+([0-9])) : ;;
+	*) die 1 "invalid argument, type $NAME_ -h for help" ;;
 esac
+n=$1
+[ $# -ge 3 ] || die 1 "missing argument, only has $#"
+[ -e $2 ] || die 1 "file $2 does not exist"
+INSERT=$2
+shift 2
+
+for A in "$@"; do
+	[ -f "$A" ] || errcho "$A does not exist or is not a file"
+	# in case we want to insert at line 1
+	if [ $n -eq 1 ];then
+		touch "$TMP1"
+		sed -n ''$n',$p' $A > "$TMP2"
+		cat "$TMP1" "$INSERT" "$TMP2" > "$A"
+		continue
+
+	fi
+
+	((n--)) # back up one line
+	sed -n '1,'$n'p' "$A" > "$TMP1"
+	((n++)) # back to original n
+	sed -n ''$n',$p' "$A" > "$TMP2"
+	cat "$TMP1" "$INSERT" "$TMP2" > "$A"
+done
diff --git a/src/bin/mvspc b/src/bin/mvspc
--- a/src/bin/mvspc
+++ b/src/bin/mvspc
@@ -1,7 +1,7 @@
 #! /bin/bash
 # #############################################################################
 
-       NAME_=`basename $0`
+       NAME_=$(basename $0)
        HTML_="remove spaces in files"
     PURPOSE_="substitute space in a file and dir name with an _"
    SYNOPSIS_="$NAME_ [-vhl] <file> [file...]"
@@ -25,41 +25,39 @@ Usage: $SYNOPSIS_
 Requires: $REQUIRES_
 Options:
      -v, verbose
-     -h, usage and options (this help)
-     -l, see this script"
+     -h, usage and options (this help)"
     exit 1
 }
 
-# args check
-[ $# -eq 0 ] && { errcho "missing argument, type $NAME_ -h for help"; exit 1; }
+die()
+{
+	RC=$1
+	shift
+	errcho "$*"
+	exit $RC
+}
 
-# var init
-verbose=false
+[ $# -eq 0 ] && die 1 "missing argument, type $NAME_ -h for help"
 
-# option and arg handling
-while getopts vhlr options; do
-
-    case "$options" in
-        v) verbose=true ;;
-        h) usage ;;
-        l) more $0; exit 1 ;;
-       \?) echo invalid argument, type $NAME_ -h for help; exit 1 ;;
-    esac
-
+VERBOSE=false
+while getopts vhlr OPTION; do
+	case $OPTION in
+		v) VERBOSE=true ;;
+		h) usage ;;
+		\?) die 1 "invalid argument, type $NAME_ -h for help" ;;
+	esac
 done
-shift $(( $OPTIND - 1 ))
+shift $((OPTIND - 1))
     
 # main execution
-for a in "$@"; do
-
-    newf=${a// /_}
-    if [[ "$a" == "$newf" ]];then
-        continue # no spaces in file name
-    elif [ -f "$newf" ] || [ -d "$newf" ]; then
-        echo "${NAME_}: not renaming \"$a\" - \"$newf\" already exist" && continue
-    else
-        $verbose && echo "renaming: \"$a\" -> \"$newf\""
-        mv -- "$a" "$newf"
-    fi
-
+for A in "$@"; do
+	NEWF=${A// /_}
+	if [ "$A" = "$NEWF" ];then
+		continue # no spaces in file name
+	elif [ -f "$NEWF" ] || [ -d "$NEWF" ]; then
+		errcho "${NAME_}: not renaming '$A' - '$NEWF' already exist" && continue
+	else
+		$VERBOSE && echo "renaming: '$A' -> '$NEWF'"
+		mv -- "$A" "$NEWF"
+	fi
 done
