git-make-patchset: rename out-dir to out
it will not always be a directory...

Signed-off-by: Idan Kedar <idank@primarydata.com>

diff --git a/src/bin/git-make-patchset b/src/bin/git-make-patchset
--- a/src/bin/git-make-patchset
+++ b/src/bin/git-make-patchset
@@ -3,7 +3,7 @@
 PROGRAM=`basename $0`
 DESCRIPTION="create a patchset to send"
 PARAMS="from-rev to-rev [remote-name]"
-OPTIONS="[-he] [-p prefix] [-v version] [-s subject] [-o out-dir]"
+OPTIONS="[-he] [-p prefix] [-v version] [-s subject] [-o out]"
 
 usage()
 {
@@ -30,9 +30,9 @@ environment variable is defined, it will be used. otherwise, if the EDITOR
 environment variable is defined, it will be used. otherwise, if vim(1) is in
 the path, it will be used. otherwise, vi(1) will be used.
 
-if out-dir is not given, the output directory will be named based on to-rev
-using git-rev-parse(1). if that doesn't work, the output directory will be
-named based on to-rev without using git-rev-parse.
+if out is not given, it will be named based on to-rev using
+git-rev-parse(1). if that doesn't work, the output directory will be named based
+on to-rev without using git-rev-parse.
 
 exit status:
 0:	success
@@ -46,7 +46,7 @@ EOF
 PREFIX=""
 VERSION=""
 SUBJECT=""
-OUTDIR=""
+OUT=""
 EDIT=false
 while getopts hp:v:s:o:e option; do
 	case $option in
@@ -54,7 +54,7 @@ while getopts hp:v:s:o:e option; do
 		p) PREFIX="$OPTARG " ;;
 		v) VERSION=" v$OPTARG" ;;
 		s) SUBJECT="$OPTARG" ;;
-		o) OUTDIR="$OPTARG" ;;
+		o) OUT="$OPTARG" ;;
 		e) EDIT=true ;;
 		\?) usage 254 ;;
 	esac
@@ -71,14 +71,14 @@ REMOTE="$3"
 VISUAL_FLAGS=()
 [[ $VISUAL =~ ^vi ]] && VISUAL_FLAGS+=("-c" "set textwidth=80")
 
-if [ -z "$OUTDIR" ]; then
+if [ -z "$OUT" ]; then
 	REF=$(git rev-parse --abbrev-ref $TO_REV)
-	OUTDIR=$(basename ${REF:-$TO_REV})
+	OUT=$(basename ${REF:-$TO_REV})
 fi
 
 
-if [ -d "$OUTDIR" ] && [ -n "$(ls -A "$OUTDIR")" ]; then
-	echo "$PROGRAM: cannot write to $OUTDIR: Directory not empty"
+if [ -d "$OUT" ] && [ -n "$(ls -A "$OUT")" ]; then
+	echo "$PROGRAM: cannot write to $OUT: Directory not empty"
 	exit 253
 fi
 
@@ -92,10 +92,10 @@ else
 	PULL_REQ=""
 fi
 
-git format-patch -U15 --cover-letter -o "$OUTDIR" --subject-prefix="${PREFIX}PATCH${VERSION}" "${FROM_REV}..${TO_REV}" || exit $?
+git format-patch -U15 --cover-letter -o "$OUT" --subject-prefix="${PREFIX}PATCH${VERSION}" "${FROM_REV}..${TO_REV}" || exit $?
 
-COVER_LETTER=$OUTDIR/0000-cover-letter.patch
-PATCHES=$(ls $OUTDIR/* | grep -vx $COVER_LETTER)
+COVER_LETTER=$OUT/0000-cover-letter.patch
+PATCHES=$(ls $OUT/* | grep -vx $COVER_LETTER)
 PATCHSET_ID="$(date +%Y%m%d%H%M%S)${VERSION:1}T"
 
 sed -i "s|\*\*\* SUBJECT HERE \*\*\*|$SUBJECT|" $COVER_LETTER
@@ -105,7 +105,7 @@ sed -i -e '/---/{n;i\' -e "\nPatchset: ${PATCHSET_ID} ${SUBJECT}\n" -e ':a;n;ba;
 rm ${COVER_LETTER}.bak
 
 if $EDIT; then
-	FILES=$OUTDIR/*
+	FILES=$OUT/*
 else
 	FILES=$COVER_LETTER
 fi
