update coding convention in git scripts
Signed-off-by: Idan Kedar <idank@primarydata.com>

diff --git a/src/bin/git-make-patchset b/src/bin/git-make-patchset
--- a/src/bin/git-make-patchset
+++ b/src/bin/git-make-patchset
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-PROGRAM=`basename $0`
+PROGRAM=$(basename $0)
 DESCRIPTION="create a patchset to send"
 PARAMS="from-rev to-rev [remote-name]"
 OPTIONS="[-he] [-p prefix | -r] [-v version] [-s subject] [-o out]"
@@ -48,6 +48,14 @@ EOF
 	exit $1
 }
 
+die()
+{
+	RC=$1
+	shift
+	errcho "$*"
+	exit $RC
+}
+
 PREFIX=""
 VERSION=""
 SUBJECT=""
@@ -80,23 +88,21 @@ VISUAL_FLAGS=()
 
 if [ -z "$OUT" ]; then
 	REF=$(git rev-parse --abbrev-ref $TO_REV)
-	OUT=$(basename ${REF:-$TO_REV})
+	OUT="$(basename ${REF:-$TO_REV})"
 fi
 
-if [ $(git rev-parse ${FROM_REV}) = $(git rev-parse ${TO_REV}^) ]; then
+if [ "$(git rev-parse ${FROM_REV})" = "$(git rev-parse ${TO_REV}^)" ]; then
 	PATCHSET=false
 	EDIT=false
-	OUT=${OUT}.patch
+	OUT="${OUT}.patch"
 else
 	PATCHSET=true
 fi
 
 if $PATCHSET && [ -d "$OUT" ] && [ -n "$(ls -A "$OUT")" ]; then
-	echo "$PROGRAM: cannot write to $OUT: Directory not empty"
-	exit 253
+	die 253 "$PROGRAM: cannot write to '$OUT': Directory not empty"
 elif ! $PATCHSET && [ -e "$OUT" ]; then
-	echo "$PROGRAM: cannot write to $OUT: File exists"
-	exit 253
+	die 253 "$PROGRAM: cannot write to '$OUT': File exists"
 fi
 
 if [ -n "$REMOTE" ]; then
@@ -110,29 +116,33 @@ else
 fi
 
 if $PATCHSET; then
-	git format-patch -U15 --cover-letter -o "$OUT" --subject-prefix="PATCH${PREFIX}${VERSION}" "${FROM_REV}..${TO_REV}" || exit $?
+	git format-patch -U15 --cover-letter -o "$OUT" \
+		--subject-prefix="PATCH${PREFIX}${VERSION}" \
+		"${FROM_REV}..${TO_REV}" || die $? "format patch failed"
 
-	COVER_LETTER=$OUT/0000-cover-letter.patch
-	PATCHES=$(ls $OUT/* | grep -vx $COVER_LETTER)
+	COVER_LETTER="$OUT/0000-cover-letter.patch"
+	PATCHES=$(ls "$OUT"/* | grep -vx "$COVER_LETTER")
 	PATCHSET_ID="$(date +%Y%m%d%H%M%S)${VERSION:1}T"
 
-	sed -i "s|\*\*\* SUBJECT HERE \*\*\*|$SUBJECT|" $COVER_LETTER
-	perl -i.bak -pe "s|\*\*\* BLURB HERE \*\*\*|$PULL_REQ|" $COVER_LETTER
-	sed -i -e '/Subject:/{n;i\' -e "\nID: $PATCHSET_ID" -e ':a;n;ba;}' $COVER_LETTER
-	sed -i -e '/---/{n;i\' -e "\nPatchset: ${PATCHSET_ID} ${SUBJECT}\n" -e ':a;n;ba;}' $PATCHES
+	sed -i "s|\*\*\* SUBJECT HERE \*\*\*|$SUBJECT|" "$COVER_LETTER"
+	perl -i.bak -pe "s|\*\*\* BLURB HERE \*\*\*|$PULL_REQ|" "$COVER_LETTER"
+	sed -i -e '/Subject:/{n;i\' -e "\nID: $PATCHSET_ID" -e ':a;n;ba;}' "$COVER_LETTER"
+	sed -i -e '/---/{n;i\' -e "\nPatchset: $PATCHSET_ID $SUBJECT\n" -e ':a;n;ba;}' "$PATCHES"
 else
-	git format-patch -U15 --stdout --subject-prefix="PATCH${PREFIX}${VERSION}" "${FROM_REV}..${TO_REV}" > "$OUT" || exit $?
+	git format-patch -U15 --stdout \
+		--subject-prefix="PATCH${PREFIX}${VERSION}" \
+		"${FROM_REV}..${TO_REV}" > "$OUT" || die $? "format patch failed"
 
-	COVER_LETTER=$OUT
+	COVER_LETTER="$OUT"
 
-	perl -i.bak -p -e "\$first=1 if(!\$first && s|^---|---\n\n$PULL_REQ\n|)" $COVER_LETTER
+	perl -i.bak -p -e "\$first=1 if(!\$first && s|^---|---\n\n$PULL_REQ\n|)" "$COVER_LETTER"
 fi
-rm ${COVER_LETTER}.bak
+rm "${COVER_LETTER}.bak"
 
 if $EDIT; then
-	FILES=$OUT/*
+	FILES="$OUT"/*
 else
-	FILES=$COVER_LETTER
+	FILES="$COVER_LETTER"
 fi
 
-$VISUAL "${VISUAL_FLAGS[@]}" $FILES
+exec $VISUAL "${VISUAL_FLAGS[@]}" $FILES
